## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## Fit and run fixed and mixed effects effects Carlina stochastic IPM
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

rm(list=ls(all=TRUE))

library(doBy)
library(lme4)
library(MCMCglmm)
library(parallel)
library(rjags)
set.seed(53241986)

## Working directory must be set here, so the source()'s below run
root=ifelse(.Platform$OS.type=="windows","c:/repos","~/Repos"); 
setwd(paste(root,"/ipm_book/Rcode/c2",sep="")); 

source("../utilities/Standard Graphical Pars.R");

root=ifelse(.Platform$OS.type=="windows","c:/repos","~/Repos"); 
setwd(paste(root,"/ipm_book/Rcode/c7/Carlina",sep="")); 

#Read in the Carlina demographic data
load("CarlinaIBMsim.Rdata")
str(sim.data)

store.sim.data <- sim.data

#Select recruit data for the last 20 years (years 31 to 50)
recr.data <- subset(sim.data,Recr==1)
recr.data <- subset(recr.data,Yeart>30)
recr.data <- transform(recr.data,Yeart = factor(Yeart - 30))

#plant data for years 30 to 49, we do this to as the recruit size in 
#year t was generated by the year t-1 parameters
sim.data <- subset(sim.data,Yeart>29 & Yeart<50)
with(sim.data,table(Yeart,Recr))
#Make Yeart a factor
sim.data <- transform(sim.data,Yeart = factor(Yeart - 29))


#fit some survival models

mod.Surv <- glm(Surv ~ Yeart  , family = binomial, data = sim.data)
mod.Surv.1 <- glm(Surv ~ Yeart + z  , family = binomial, data = sim.data)
mod.Surv.2 <- glm(Surv ~ Yeart * z  , family = binomial, data = sim.data)

anova(mod.Surv,mod.Surv.1,mod.Surv.2,test="Chisq")
AIC(mod.Surv,mod.Surv.1,mod.Surv.2)

#there is evidence of an interaction, as we might expect as both the intercept and slope vary from 
#year to year

#Let's refit so we can easily get the parameter estimates

mod.Surv <- glm(Surv ~ Yeart/z -1 , family = binomial, data = sim.data)

summary(mod.Surv)

#Let's refit using glmer

mod.Surv.glmer   <- glmer(Surv ~ 1 + (1|Yeart)  , family = binomial, data = sim.data)
mod.Surv.glmer.1 <- glmer(Surv ~ z + (1|Yeart)  , family = binomial, data = sim.data)
mod.Surv.glmer.2 <- glmer(Surv ~ z + (1|Yeart) + (0 + z|Yeart)  , family = binomial, data = sim.data)
mod.Surv.glmer.3 <- glmer(Surv ~ z + (z|Yeart)  , family = binomial, data = sim.data)
anova(mod.Surv.glmer,mod.Surv.glmer.1,mod.Surv.glmer.2,mod.Surv.glmer.3)



# # d<-1
# prior=list(R=list(V=1, fix=1), G=list(G1=list(V=diag(d), nu=d, alpha.mu=rep(0,d), alpha.V=diag(d)*1000)))

# mod.Surv.MCMC   <- MCMCglmm(Surv ~ 1, random=~Yeart  , family = "categorical", data = sim.data,
# slice=TRUE, pr=TRUE,prior=prior)

# mod.Surv.MCMC.1   <- MCMCglmm(Surv ~ z, random=~Yeart  , family = "categorical", data = sim.data,
# slice=TRUE, pr=TRUE,prior=prior)

# d<-2
# prior=list(R=list(V=1, fix=1), G=list(G1=list(V=diag(d), nu=d, alpha.mu=rep(0,d), alpha.V=diag(d)*1000)))

# mod.Surv.MCMC.2  <- MCMCglmm(Surv ~ z, random=~idh(1+z):Yeart  , family = "categorical", data = sim.data,
# slice=TRUE, pr=TRUE,prior=prior)

# mod.Surv.MCMC.3   <- MCMCglmm(Surv ~ z, random=~us(1+z):Yeart  , family = "categorical", data = sim.data,
# slice=TRUE, pr=TRUE,prior=prior)

# post.modes <- posterior.mode(mod.Surv.MCMC.2$Sol)

# intercepts.MCMC <- post.modes["(Intercept)"] + post.modes[3:22]

# slopes.MCMC <- post.modes["z"] + post.modes[23:42]

# par(mfrow=c(1,2),bty="l",pty="s",pch=19)

# plot(intercepts.MCMC,coef(mod.Surv.glmer.2)$Yeart[,"(Intercept)"])
# abline(0,1,col="red")
# plot(slopes.MCMC,coef(mod.Surv.glmer.2)$Yeart[,"z"])
# abline(0,1,col="red")


#fit some flowering models

flow.data <- subset(sim.data,Surv==1)

mod.Flow <- glm(Flow ~ Yeart  , family = binomial, data = flow.data)
mod.Flow.1 <- glm(Flow ~ Yeart + z  , family = binomial, data = flow.data)
mod.Flow.2 <- glm(Flow ~ Yeart * z  , family = binomial, data = flow.data)

anova(mod.Flow,mod.Flow.1,mod.Flow.2,test="Chisq")
AIC(mod.Flow,mod.Flow.1,mod.Flow.2)

#No interaction term, as expected, refit to get paramter estimates easily

mod.Flow <- glm(Flow ~ Yeart + z -1 , family = binomial, data = flow.data)

#Let's refit using glmer

mod.Flow.glmer   <- glmer(Flow ~ 1 + (1|Yeart)  , family = binomial, data = flow.data)
mod.Flow.glmer.1 <- glmer(Flow ~ z + (1|Yeart)  , family = binomial, data = flow.data)
mod.Flow.glmer.2 <- glmer(Flow ~ z + (1|Yeart) + (0 + z|Yeart)  , family = binomial, data = flow.data)
mod.Flow.glmer.3 <- glmer(Flow ~ z + (z|Yeart)  , family = binomial, data = flow.data)
anova(mod.Flow.glmer,mod.Flow.glmer.1,mod.Flow.glmer.2,mod.Flow.glmer.3)

#fit some growth models

grow.data <- subset(sim.data,Surv==1 & Flow==0)

mod.Grow <- lm(z1 ~ Yeart  , data = grow.data)
mod.Grow.1 <- lm(z1 ~ Yeart +z , data = grow.data)
mod.Grow.2 <- lm(z1 ~ Yeart *z , data = grow.data)

anova(mod.Grow,mod.Grow.1,mod.Grow.2)
AIC(mod.Grow,mod.Grow.1,mod.Grow.2)

mod.Grow <- lm(z1 ~ Yeart/z-1  , data = grow.data)

#Let's refit using lmer

mod.Grow.lmer   <- lmer(z1 ~ 1 + (1|Yeart)  ,  data = grow.data, REML=FALSE)
mod.Grow.lmer.1 <- lmer(z1 ~ z + (1|Yeart)  ,  data = grow.data, REML=FALSE)
mod.Grow.lmer.2 <- lmer(z1 ~ z + (1|Yeart) + (0 + z|Yeart)  ,  data = grow.data, REML=FALSE)
mod.Grow.lmer.3 <- lmer(z1 ~ z + (z|Yeart)  ,  data = grow.data, REML=FALSE)
anova(mod.Grow.lmer,mod.Grow.lmer.1,mod.Grow.lmer.2,mod.Grow.lmer.3)

#fit some recruit size models

mod.Rcsz <- lm(z ~ 1  , data = recr.data)
mod.Rcsz.1 <- lm(z ~ Yeart , data = recr.data)

anova(mod.Rcsz,mod.Rcsz.1)
AIC(mod.Rcsz,mod.Rcsz.1)

mod.Rcsz <- lm(z ~ Yeart -1, data = recr.data)

#Let's refit using lmer

mod.Rcsz.lmer <- lmer(z ~ 1 + (1|Yeart) , data = recr.data)

#quick check

plot(as.numeric(coef(mod.Rcsz)),unlist(coef(mod.Rcsz.lmer)$Yeart))
abline(0,1)

#plot intercepts quick check

plot(coef(mod.Grow)[1:20],coef(mod.Rcsz))
cor.test(coef(mod.Grow)[1:20],coef(mod.Rcsz))

##################################################################################
#fit bivariate model using Cam formulation
N1 <- length(grow.data$z)
N2 <- N1+length(recr.data$z)

lst <- grow.data$z 
lst1 <- grow.data$z1
rec.size <- recr.data$z
yeart <- grow.data$Yeart
rec.yeart <- recr.data$Yeart

#plot(coef(lm(rec.size~rec.yeart-1)),coef(lm(lst1~yeart/lst-1))[1:20])

#####################################################################################################################################
#fit it with BUGS Cam formulation

n.chains=3;

rho=0.76
a=rnorm(1,1,0.1)
b=rnorm(1,1,0.1)

X=c(lst,rep(NA,length(rec.size))); Y=c(lst1,rec.size); ngroup=20; group=c(yeart,rec.yeart);

#data=list("N1","N2","X","Y","ngroup","group"); 

data = list(N1=N1,N2=N2,X=X,Y=Y,ngroup=ngroup,group=group)

inits=function() {
	list(mu.A=1.17,mu.Ar=3.18,B=0.71,
	     prec.B=100,prec.e=12,prec.er=4,a=a,b=b,rho=rho,
	     x=rnorm(ngroup,0.0,1),y=rnorm(ngroup,0.0,1),B.g=rnorm(ngroup)
	    )
}

# # inits=function() {
	# list(mu.A=rnorm(1,0,1),mu.Ar=rnorm(1,0,1),B=rnorm(1,0,1),
	     # prec.B=rnorm(1,1,0.1),prec.e=rnorm(1,1,0.1),prec.er=rnorm(1,1,0.1),a=a,b=b,rho=rho,
	     # x=rnorm(ngroup,0.0,1),y=rnorm(ngroup,0.0,1),B.g=rnorm(ngroup)
	    # )
# }


parameters=c("mu.A","mu.Ar","B","sd.B","rho","sd.e","sd.er","sd.A","sd.Ar");

# glmm.sim=jags.model(data=data,inits=inits,
# file="model grow rec Car.txt",n.chains=n.chains)
# samps <- coda.samples(glmm.sim,parameters,n.iter=400000,thin=1000)
#save(samps,file="MCMCsamples.Rdata")
load(file="MCMCsamples.Rdata")
plot(samps[,1:4])
plot(samps[,5:8])
plot(samps[,9])
#gelman.plot(samps)
autocorr.plot(samps)


burn.in <- 100000
summary.posterior <- summary(window(samps, start=burn.in))
summary.posterior

#set up parameter vector for fixed effects from mixed models


m.par.est <- c(## survival
				surv.int = as.numeric(fixef(mod.Surv.glmer.2)["(Intercept)"]),
				surv.z = as.numeric(fixef(mod.Surv.glmer.2)["z"]),
				## flowering
				flow.int = as.numeric(fixef(mod.Flow.glmer.1)["(Intercept)"]),
				flow.z = as.numeric(fixef(mod.Flow.glmer.1)["z"]),
				## growth
				grow.int = summary.posterior$statistics["mu.A","Mean"],
				grow.z = summary.posterior$statistics["B","Mean"],
				grow.sd = summary.posterior$statistics["sd.e","Mean"],
				## recruit size
				rcsz.int = summary.posterior$statistics["mu.Ar","Mean"],
				rcsz.sd = summary.posterior$statistics["sd.er","Mean"],
				## seed size
				seed.int = 1,
				seed.z = 2,
				## recruitment probability
				p.r = 0.00095)

m.par.sd.est <- c(## survival
                surv.int.sd        =   as.data.frame(VarCorr(mod.Surv.glmer.2))[1,5],
                surv.z.sd           =   as.data.frame(VarCorr(mod.Surv.glmer.2))[2,5],
                ## flowering
                flow.int.sd       =  as.data.frame(VarCorr(mod.Flow.glmer.1))[1,5],
                flow.z.sd          =   0.0,
                ## growth
                grow.int.sd         =   summary.posterior$statistics["sd.A","Mean"],
                grow.z.sd            =   summary.posterior$statistics["sd.B","Mean"],
                grow.sd.sd          =  0.0,
                ## recruit size
                rcsz.int.sd       =   summary.posterior$statistics["sd.Ar","Mean"], 
                rcsz.sd.sd       =   0.0,
                ## seed size
                seed.int.sd  =   0.0,
                seed.z.sd     =   0.0,
                ## recruitment probability
                p.r.sd           =   0.00) 

save(m.par.est,m.par.sd.est,file="Mixed model parameters.Rdata")

source("Carlina Demog Funs DI.R") 


cov.growth.rec <-summary.posterior$statistics["rho","Mean"] * summary.posterior$statistics["sd.A","Mean"] * summary.posterior$statistics["sd.Ar","Mean"]

cov.matrix <- matrix(c(summary.posterior$statistics["sd.A","Mean"]^2, cov.growth.rec, cov.growth.rec, 
summary.posterior$statistics["sd.Ar","Mean"]^2),nrow=2)

cov.matrix
VarCovar.grow.rec
cov2cor(cov.matrix)
cov2cor(VarCovar.grow.rec)

chol.cov.matrix <- chol(cov.matrix)


#Test we've recreated what we started with

par(mfrow=c(1,2),pty="s", bty="l",pch=19)
plot(m.par.est,m.par.true)
abline(0,1)
plot(m.par.sd.est,m.par.sd.true)
abline(0,1)



#####################################################################
#Run stochastic fixed effects IPM
#####################################################################

# # # #generate a long parameter vector for LTRE
# n.est=5000
# store.params <- matrix(NA,nrow=12,ncol=n.est)
# for (year.t in 1:n.est){
		# if(year.t%%1000==0) cat("iterate: ", year.t,"\n");

		# #params.t<-rnorm(11,params,sd.vec)

		# params.t=m.par.est + qnorm(runif(12,0.001,0.999))*m.par.sd.est

		# #sample from multivariate normal distribution for growth intercepts and yearly mean recruit size
		# #params.t[c(5,10)]<-mvrnorm(1,mean.grow.rec,VarCovar.grow.rec)

		# params.t[c("grow.int","rcsz.int")] <- m.par.est[c("grow.int","rcsz.int")]+matrix(qnorm(runif(2,0.001,0.999)),1,2) %*% chol.cov.matrix 

		# store.params[,year.t] <- params.t
		# }
	
# rownames(store.params) <- names(m.par.est)
		
# save(store.params,file="Big param matrix.Rdata")

iterate_model<-function(params,params.sd,chol.mat,n.est) { 
		
	nt<-rep(1/nBigMatrix,nBigMatrix)
	Rt<-rep(NA,n.est)
	size.dist<-rep(0,nBigMatrix)
	size.dist.fl<-rep(0,nBigMatrix)

	for (year.t in 1:n.est){
		if(year.t%%1000==0) cat("iterate: ", year.t,"\n");

		#params.t<-rnorm(11,params,sd.vec)

		params.t=params + qnorm(runif(12,0.001,0.999))*params.sd

		#sample from multivariate normal distribution for growth intercepts and yearly mean recruit size
		#params.t[c(5,10)]<-mvrnorm(1,mean.grow.rec,VarCovar.grow.rec)

		params.t[c("grow.int","rcsz.int")] <- params[c("grow.int","rcsz.int")]+matrix(qnorm(runif(2,0.001,0.999)),1,2) %*% chol.mat 
		
		year.K<-mk_K(nBigMatrix,params.t,minsize,maxsize)
	
		

		nt1<-year.K$K %*% nt
	
		sum.nt1<-sum(nt1)
		
		Rt[year.t]<-log(sum.nt1)

		dist.fl.year <- nt * s_z(year.K$meshpts,params.t) * p_bz(year.K$meshpts,params.t)

		size.dist <- size.dist + nt

		size.dist.fl<-size.dist.fl+dist.fl.year

		nt <- nt1 / sum(nt1)
		
	}

   
	
	size.dist <- size.dist / sum(size.dist)
	size.dist.fl <- size.dist.fl / sum(size.dist.fl)
	
	return(list(size.dist=size.dist,size.dist.fl=size.dist.fl,
		    Rt=Rt,meshpts=year.K$meshpts))
}


##run model and plot some graphs


nBigMatrix <- 100
n.est <- 50000
n.runin <- 500
minsize <- 1.5
maxsize <- 5


##########################
#First let's iterate the model using the estimated mixed model parameters

iter <- iterate_model(m.par.est,m.par.sd.est,chol.cov.matrix,n.est)

stoch.lambda <- mean(iter$Rt[n.runin:n.est],na.rm=T)
SE.stoch.lambda <- sd(iter$Rt[n.runin:n.est],na.rm=T) / sqrt(length(iter$Rt[n.runin:n.est]))
cat("Stochastic growth rate IPM =",stoch.lambda,"\n")
cat("Approximate 95% CI for stochastic growth rate from IPM ",stoch.lambda + 2*SE.stoch.lambda, " to ", stoch.lambda - 2*SE.stoch.lambda,"\n")

#from IPM (log scale)
sum(iter$size.dist * iter$meshpts)

#from IPM
sum(iter$size.dist.fl * exp(iter$meshpts))


#Lots of iterations - takes a while as we have to build the kernel each iteration

nBigMatrix <- 100
n.est <- 500000
n.runin <- 500
minsize <- 1.5
maxsize <- 5


iter <- iterate_model(m.par.est,m.par.sd.est,chol.cov.matrix,n.est)

stoch.lambda <- mean(iter$Rt[n.runin:n.est],na.rm=T)
SE.stoch.lambda <- sd(iter$Rt[n.runin:n.est],na.rm=T) / sqrt(length(iter$Rt[n.runin:n.est]))
cat("Stochastic growth rate IPM =",stoch.lambda,"\n")
cat("Approximate 95% CI for stochastic growth rate from IPM ",stoch.lambda + 2*SE.stoch.lambda, " to ", stoch.lambda - 2*SE.stoch.lambda,"\n")

#from IPM (log scale)
sum(iter$size.dist * iter$meshpts)

#from IPM
sum(iter$size.dist.fl * exp(iter$meshpts))






